function refreshAdmin(){
 const exams=getExams(), students=getStudents(), results=getResults();
 document.getElementById("studentCount").textContent=students.length;
 document.getElementById("examCount").textContent=exams.length;
 document.getElementById("resultCount").textContent=results.length;
 document.getElementById("questionCount").textContent=exams.reduce((n,e)=>n+e.questions.length,0);
 document.getElementById("examSelect").innerHTML=exams.map(e=>`<option value="${e.id}">${e.title}</option>`).join("");
 document.getElementById("examRows").innerHTML=exams.map(e=>`<tr><td>${e.title}</td><td>${e.subject}</td><td>${e.grade}</td><td>${e.questions.length}</td><td>${e.duration} min</td><td>${e.passMark}%</td></tr>`).join("");
 document.getElementById("allResultRows").innerHTML=results.slice().reverse().map(r=>{const s=students.find(x=>x.id===r.studentId);return `<tr><td>${r.candidateName||s?.name||"Unknown"}</td><td>${r.candidateId||"—"}</td><td>${r.studentId}</td><td>${r.examTitle}</td><td>${r.obtainedMarks}/${r.totalMarks}</td><td>${r.percentage}%</td><td>${r.grade}</td><td><span class="status ${r.status.toLowerCase()}">${r.status}</span></td><td>${formatDate(r.date)}</td></tr>`}).join("")||'<tr><td colspan="9" class="empty">No results.</td></tr>';
}
function parseCSV(text){
 const rows=[];let row=[],cell="",quote=false;
 for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quote&&n==='"'){cell+='"';i++}else if(c==='"'){quote=!quote}else if(c===","&&!quote){row.push(cell.trim());cell=""}else if((c==="\n"||c==="\r")&&!quote){if(c==="\r"&&n==="\n")i++;row.push(cell.trim());cell="";if(row.some(x=>x!==""))rows.push(row);row=[]}else cell+=c}
 if(cell!==""||row.length){row.push(cell.trim());if(row.some(x=>x!==""))rows.push(row)}
 return rows;
}
let pendingQuestions=[],pendingSource="";
document.getElementById("examFile").addEventListener("change",()=>{document.getElementById("importMessage").innerHTML="";document.getElementById("preview").innerHTML="";document.getElementById("confirmImportArea").classList.add("hidden");pendingQuestions=[];});
async function importSelectedFile(){const file=document.getElementById("examFile").files[0];if(!file){alert("Choose a CSV or DOCX file.");return}try{if(file.name.toLowerCase().endsWith(".docx")){pendingSource="Word";if(typeof mammoth==="undefined")throw new Error("Word reader unavailable. Check internet access and try again.");const r=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});previewWord(r.value)}else{pendingSource="CSV";previewCSV(await file.text())}}catch(e){document.getElementById("importMessage").innerHTML='<div class="alert error">'+escapeAdmin(e.message)+'</div>'}}
function parseCSV(t){const rows=[];let row=[],cell="",q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell.trim());cell=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell.trim());cell="";if(row.some(x=>x!==""))rows.push(row);row=[]}else cell+=c}if(cell!==""||row.length){row.push(cell.trim());if(row.some(x=>x!==""))rows.push(row)}return rows}
function previewCSV(t){pendingQuestions=[];const rows=parseCSV(t),errors=[];if(rows.length<2){showPreview(["CSV has no question rows."]);return}const h=rows[0].map(x=>x.toLowerCase().trim()),need=["question","option a","option b","option c","option d","correct answer","marks"];const miss=need.filter(x=>!h.includes(x));if(miss.length){showPreview(["Missing columns: "+miss.join(", ")]);return}const ix=Object.fromEntries(need.map(x=>[x,h.indexOf(x)]));rows.slice(1).forEach((r,n)=>{const q=r[ix.question],o=["option a","option b","option c","option d"].map(x=>r[ix[x]]),a=(r[ix["correct answer"]]||"").toUpperCase(),m=Number(r[ix.marks]||1);if(!q||o.some(x=>!x)||!["A","B","C","D"].includes(a)||!Number.isFinite(m)||m<=0)errors.push("Row "+(n+2)+": invalid question/options/answer/marks");else pendingQuestions.push({id:crypto.randomUUID(),question:q,options:o,correctAnswer:a,marks:m})});showPreview(errors)}
function previewWord(t){pendingQuestions=[];const errors=[],lines=t.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let q=null,o={},a="",m=1,num="";function flush(){if(!q)return;if(!o.A||!o.B||!o.C||!o.D||!["A","B","C","D"].includes(a))errors.push("Question "+(num||"?")+": missing option(s) or invalid Answer");else pendingQuestions.push({id:crypto.randomUUID(),question:q,options:[o.A,o.B,o.C,o.D],correctAnswer:a,marks:Number(m)||1});q=null;o={};a="";m=1}for(const line of lines){let z=line.match(/^(?:Q(?:uestion)?\s*)?(\d+)[.)]\s*(.+)$/i),x=line.match(/^([ABCD])[.)]\s*(.+)$/i),y=line.match(/^(?:Correct\s*)?(?:Answer|Ans)\s*[:=-]\s*([ABCD])$/i),w=line.match(/^Marks?\s*[:=-]\s*([0-9]+(?:\.[0-9]+)?)$/i);if(z){flush();num=z[1];q=z[2].trim()}else if(x&&q)o[x[1].toUpperCase()]=x[2].trim();else if(y&&q)a=y[1].toUpperCase();else if(w&&q)m=Number(w[1]);else if(q&&Object.keys(o).length===0)q+=" "+line}flush();if(!pendingQuestions.length&&!errors.length)errors.push("No questions detected. Use the Word Format Guide.");showPreview(errors)}
function showPreview(errors){document.getElementById("importMessage").innerHTML=errors.length?'<div class="alert error">'+errors.map(escapeAdmin).join("<br>")+'</div>':'<div class="alert success">'+pendingQuestions.length+' valid '+pendingSource+' question(s) ready. Review before importing.</div>';document.getElementById("preview").innerHTML=pendingQuestions.length?'<div class="table-wrap"><table><thead><tr><th>#</th><th>Question</th><th>A</th><th>B</th><th>C</th><th>D</th><th>Correct</th><th>Marks</th></tr></thead><tbody>'+pendingQuestions.map((q,i)=>'<tr><td>'+(i+1)+'</td><td>'+escapeAdmin(q.question)+'</td>'+q.options.map(x=>'<td>'+escapeAdmin(x)+'</td>').join('')+'<td>'+q.correctAnswer+'</td><td>'+q.marks+'</td></tr>').join('')+'</tbody></table></div>':'';document.getElementById("confirmImportArea").classList.toggle("hidden",!pendingQuestions.length)}
function confirmImport(){const exams=getExams(),e=exams.find(x=>x.id===document.getElementById("examSelect").value);if(!e)return;e.questions.push(...pendingQuestions);saveExams(exams);document.getElementById("importMessage").innerHTML='<div class="alert success">Imported '+pendingQuestions.length+' question(s) from '+pendingSource+' into '+e.title+'.</div>';pendingQuestions=[];document.getElementById("preview").innerHTML="";document.getElementById("confirmImportArea").classList.add("hidden");document.getElementById("examFile").value="";refreshAdmin()}
function escapeAdmin(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}refreshAdmin();
